repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        files: ^backend/
      - id: end-of-file-fixer
        files: ^backend/
      - id: trailing-whitespace
        files: ^backend/
      - id: check-added-large-files
        files: ^backend/
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.2
    hooks:
      - id: autopep8
        files: ^backend/
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^backend/
        name: isort (python)
        args: [ --settings-path, backend/setup.cfg ]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        files: ^backend/
        additional_dependencies:
          - pyproject-flake8
          - flake8-builtins
          - flake8-bugbear
          - flake8-quotes
          - flake8-eradicate
          - flake8-mock
          - flake8-pie
          - flake8-print
          - flake8-printf-formatting
          - flake8-pytest-style
          - flake8-variables-names
        args: [ "--config=backend/setup.cfg" ]
  - repo: local
    hooks:
      - id: migrations
        files: ^backend/
        name: "Checking migrations"
        entry: python backend/manage.py
        language: system
        args: [ makemigrations, --dry-run, --check ]
        pass_filenames: false
        require_serial: true
